### PR TITLE
Bump PHP versions

### PR DESCRIPTION
**Pull request by adhocore**

### CODE REVIEW

**Comment by adhocore** [comment]
thanks for the words. i hope soon like this weekend. btw 8.3r to 8.3 may need some fight to get it mainstream

**Comment by adhocore** [comment]
@fernando1419 would you give it a try once? :D 
it would be your chance to contribute, thanks

**Comment by fernando1419** [comment]
> @fernando1419 would you give it a try once? :D it would be your chance to contribute, thanks

I'd be glad to git it a try, just let me know once you get it done. Thanks again fellow!. Regards.

**Comment by adhocore** [comment]
no i mean to contribute PR for 8.3 change :)

**Comment by fernando1419** [comment]
Oh, I got you. Great, I'll be working on it as soon as I have some free time.

**Pull request merged**
