### PR TITLE
8.4 upgrade

### PR DESCRIPTION
**Pull request by gogl92**
It still need work to do but it can work as a sneak peek.

Should cover #106

### CODE REVIEW

**Review by adhocore — COMMENTED** [review]
oops seems i missed this PR for some reason, may be the notification mixed up among issues/prs

**Review by adhocore — APPROVED** [review]

**Comment by adhocore** [comment]
thank you :)

**Comment by adhocore** [comment]
seems build has failed. https://github.com/adhocore/docker-phpfpm/actions/runs/12295442117/job/34312334042 (issue with imap ext?)

ideally, the new dockerfile should be first built in local machine to find out possible issues.

**Comment by gogl92** [comment]
> seems build has failed. https://github.com/adhocore/docker-phpfpm/actions/runs/12295442117/job/34312334042 (issue with imap ext?)
> 
> ideally, the new dockerfile should be first built in local machine to find out possible issues. 

Sorry I was away from the keyboard these days I may have run the wrong image locally I'll take a look tomorrow.

**Pull request merged**
